version: '2'
services:
    frontend-app:
        image: frontend
        external_links:
            - frontend-mysql:mysql
            - frontend-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/frontend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    frontend-mysql:
        extends:
            file: mysql.yml
            service: frontend-mysql
    frontend-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: frontend-elasticsearch
